### PR TITLE
Upgrade to 3.3.7 and add "inserted.bs.modal" event for pre-processing

### PR DESCRIPTION
**Pull request by ElMassimo**
Besides the update to `3.3.7`, this pull request adds the `inserted.bs.modal` event, which is fired when the HTML is in the DOM and ready to be displayed, but the transition (if any) has not been started yet.

We need this event in order to apply some plugins (such as datepickers) before a modal is displayed, which is not possible with stock Bootstrap (I have [opened an issue](https://github.com/twbs/bootstrap/issues/22410) though). It comes in handy to be able to bind to an event that is triggered before transitions are started, so that plugins like selectize can be applied before the user sees the modal, which creates a jarring effect.

### CODE REVIEW

**Review by nickcherry — APPROVED** [review]
Bootstrap, putting the BS in web development.

__MM:__ :rofl:

**Review by markusos — APPROVED** [review]
Just interested, why do we have a fork of bootstrap-sass, do we have any changes that we should try getting merged into master?

**Review by ziolmar — APPROVED** [review]

**Comment by ElMassimo** [comment]
@markusos Please read the PR description 😄

**Comment by markusos** [comment]
@ElMassimo Oh, by some reason I thought the `inserted.bs.modal` was part of the 3.3.7 update, and not something we added

**Comment by ElMassimo** [comment]
Yeah, sorry, completely understand why. I'll rephrase it 😃

**Pull request merged**
